# Generated by Django 5.1.8 on 2026-06-17 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("reachstacker", "Reachstacker"),
                            ("side_shifter", "Side Shifter"),
                            ("forklift", "Forklift"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Main Controller, GPS Unit",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "device_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, unpack_ipv4=True
                    ),
                ),
                (
                    "device_status",
                    models.CharField(
                        blank=True, default="Active", max_length=50, null=True
                    ),
                ),
                (
                    "other_info",
                    models.TextField(
                        blank=True,
                        help_text="Any additional specifications or details",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="vehicles.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "name")},
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Front Cam, Rear Cam, Cabin Cam", max_length=100
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unpack_ipv4=True)),
                ("port", models.IntegerField(default=80)),
                (
                    "rtsp_url",
                    models.CharField(
                        blank=True,
                        help_text="rtsp://username:password@ip:port/stream",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
    ]
