# Generated by Django 5.1.8 on 2026-06-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="box_number",
            field=models.CharField(
                blank=True, help_text="Telemetry Box Number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_number",
            field=models.CharField(
                blank=True,
                help_text="Registration or Fleet Number",
                max_length=50,
                null=True,
            ),
        ),
    ]
