# Generated by Django 5.1.8 on 2026-07-01 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_vehicle_box_number_vehicle_vehicle_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("busy", "Busy"),
                    ("break", "On Break"),
                    ("maintenance", "Under Maintenance"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="driver_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="driver_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="DeviceIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_date_time",
                    models.DateTimeField(help_text="Issue date and time"),
                ),
                ("problem_details", models.TextField(help_text="Problem details")),
                (
                    "temp_solution_applied",
                    models.BooleanField(
                        default=False, help_text="Temporary solution applied or not"
                    ),
                ),
                (
                    "permanent_solution_required",
                    models.BooleanField(
                        default=True, help_text="Permanent solution required"
                    ),
                ),
                (
                    "permanent_solution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("working", "Working"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        help_text="Permanent solution completed or pending status like (in progress, working, on hold etc)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_issues",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date_time"],
            },
        ),
    ]
