# Generated by Django 5.1.8 on 2026-07-01 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_task_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceissue",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Technician assigned to resolve this issue",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
