# Generated by Django 5.1.8 on 2026-07-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0006_site_present_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Terminal Director"),
                    ("mid_level", "Operations Manager"),
                    ("technician", "Fleet Engineer"),
                ],
                default="technician",
                max_length=20,
            ),
        ),
    ]
