# Generated by Django 5.1.8 on 2026-07-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0007_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("mid_level", "Sub Admin"),
                    ("technician", "Ground Operations"),
                ],
                default="technician",
                max_length=20,
            ),
        ),
    ]
